version: '3'
services:
    nginx:
        build: ./docker/nginx
        ports:
          - '80:80'
          - '443:443'
        restart: always
        volumes:
            - ./docker/.data/nginx/log/:/var/log/nginx
            - ./docker/nginx/conf:/etc/nginx/conf.d/:ro
            - ./docker/certs:/etc/nginx/certs
            - ./:/var/www/html
            - ./se3/Projects/:/var/www/html
        depends_on:
            - php
    php:
      build:
        context: ./
        dockerfile: docker/php-fpm/Dockerfile
      volumes:
        - ./:/var/www/se3
        - ./se3/Projects/:/var/www/html
        - ./docker/php-fpm/supervisor:/etc/supervisor/conf.d
      depends_on:
        - mysql
    mysql:
      image: mysql:5.7.36
      volumes:
        - ./dump.sql:/docker/dbdump/admin.sql
        - ./docker/docker/dbdump:/var/dump
        - ./docker/.data/mysql:/var/lib/mysql
      ports:
        - ${MYSQL_EXTERNAL_PORT}:${MYSQL_PORT}
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    rabbitmq:
      image: rabbitmq:3.7-management
      ports: [5672,15672]